
package com.mailsigner.control.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MailSignerServiceImplService", targetNamespace = "http://ws.control.mailsigner.com/", wsdlLocation = "http://localhost:9999/ws/mailsigner?wsdl")
public class MailSignerServiceImplService
    extends Service
{

    private final static URL MAILSIGNERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.mailsigner.control.ws.MailSignerServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.mailsigner.control.ws.MailSignerServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9999/ws/mailsigner?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9999/ws/mailsigner?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MAILSIGNERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public MailSignerServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MailSignerServiceImplService() {
        super(MAILSIGNERSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://ws.control.mailsigner.com/", "MailSignerServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns MailSignerService
     */
    @WebEndpoint(name = "MailSignerServiceImplPort")
    public MailSignerService getMailSignerServiceImplPort() {
        return super.getPort(new QName("http://ws.control.mailsigner.com/", "MailSignerServiceImplPort"), MailSignerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MailSignerService
     */
    @WebEndpoint(name = "MailSignerServiceImplPort")
    public MailSignerService getMailSignerServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.control.mailsigner.com/", "MailSignerServiceImplPort"), MailSignerService.class, features);
    }

}
